/// Flutter icons DimexaIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DimexaIcons
///      fonts:
///       - asset: fonts/DimexaIcons.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class DimexaIcons {
  DimexaIcons._();

  static const _kFontFam = 'DimexaIcons';
  static const String? _kFontPkg = null;

  static const IconData collect = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData products = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delivery = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData historical = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData letters = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData documents = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData complains = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData competence = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
